language: ruby
rvm:
  - 2.3
before_install:
  - npm install
install: gem install jekyll html-proofer
script: gulp travis
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
cache:
  bundler: true
  directories:
    - "node_modules"
